spring.application.name=sk-marathon

spring.datasource.url=jdbc:postgresql://localhost:5432/sk_marathon_db
spring.datasource.username=postgres
spring.datasource.password=your_password

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8080
